Polygon extraction
TeamprojektDomaincreator/domaincreator pull request #15
Opened 2024-06-08 13:14 UTC by luis-stumpf

2024-06-08 15:04 UTC, timothyhale requested changes

2024-06-08 15:04 UTC, timothyhale commented on src/outline.ts
> +        const index = this.points.indexOf(point);
Maybe handle `index = -1` here

2024-06-08 15:04 UTC, timothyhale commented on src/outline.ts
> +    const efficientMatrix = new SpaceEfficientAdjacencyMatrix(linesSorted);
Why are you creating a efficient matrix here and not use it later on? 
If you just want unique points, use `UniquePoints`, otherwise you are paying for creating the ajdacency matrix aswell, which you create in the next steps anyway.

2024-06-08 15:04 UTC, timothyhale commented on src/cycles.ts
> +        if (matrix.getCell(vertexIndex, i)) {
do not do this with the `SpaceEfficientMatrix` . If you are going through every element, and not just the ones that actually have a connection, the cost of getting the cell content is massive. Just use a regular matrix instead and pay the cost of higher memory usage.

2024-06-08 15:04 UTC, timothyhale commented on src/cycles.ts
> +    const matrix = new SpaceEfficientAdjacencyMatrix(graph);
Here aswell, just use `UniquePoints`, or otherwise you will be constructing the connections as well, which you aren't using.

2024-06-08 15:04 UTC, timothyhale commented on src/utils.ts
> +export function createLinesFromPoints(points: Point[]): UnorderdLineSegment[] {
Just wondering if this is actually needed. Dont we just need the Points in the specific order?
like this:
` [p1, p2, p2, p3, p3, p4, ...]` would make it easier to read out just a Point list.
Not really sure.

2024-06-08 16:16 UTC, timothyhale commented on test-files/~womans-hostel-minimal.dxf
Isn't this already in  the repo?

2024-06-15 10:49 UTC, luis-stumpf commented on src/cycles.ts
> +    const matrix = new SpaceEfficientAdjacencyMatrix(graph);
they are used in the recursive cycle

2024-06-18 18:14 UTC, luis-stumpf commented
@timothyhale bitte abstempeln

2024-06-20 10:44 UTC, timothyhale commented on src/cycles.ts
> +    const matrix = new SpaceEfficientAdjacencyMatrix(graph);
Don't use the matrix here, just create UniquePoints. In the _dfsForCycles, you are iterating through each point in the matrix, even ones that don't have a connection, which makes the spaceefficientmatrix basically useless. Just use a regular matrix.

2024-06-20 10:44 UTC, timothyhale commented on src/cycles.ts
> +    console.log(connect.length)
Do we want the log statement in our release?

2024-06-20 10:44 UTC, timothyhale commented on src/eFlowTranslation.ts
> +    console.log('outerPoints: ', outerPoints);
Log necessary here?

2024-06-21 15:19 UTC, timothyhale approved these changes

2024-06-22 11:07 UTC, merged